#!/usr/bin/env bash

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors 
source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
DYNAMIC_ISLAND_DIR="$HOME/.config/sketchybar/plugins/Dynamic-Island-Sketchybar"

SPACE_CLICK_SCRIPT="yabai -m space --focus \$SID 2>/dev/null" # The script that is run for clicking on space components

source "$DYNAMIC_ISLAND_DIR/item.sh" # Loads Dynamic-Island item

# helper process
HELPER=git.felix.helper
killall helper
cd $HOME/.config/sketchybar/helper && make
$HOME/.config/sketchybar/helper/helper $HELPER > /dev/null 2>&1 &

FONT="SF Pro"

# Set up your own custom sketchybar config here
sketchybar --bar	color=$TRANSPARENT \
					margin=0		 \
					blur_radius=20                                    \
					corner_radius=0 \
					padding_right=14                                  \
					padding_left=14

ITEM_CORNER_RADIUS=3
ITEM_BACKGROUND_HEIGHT=26
ITEM_PADDING=14

source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"
source "$ITEM_DIR/mail.sh"
source "$ITEM_DIR/power.sh"
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/network.sh"

source "$ITEM_DIR/bracket_r.sh"
source "$ITEM_DIR/bracket_l.sh"

sketchybar --update
