#!/usr/bin/env sh

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors 
source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

# helper process
HELPER=git.felix.helper
killall helper
cd $HOME/.config/sketchybar/helper && make
$HOME/.config/sketchybar/helper/helper $HELPER &

ISLANDHELPER=git.crissnb.islandhelper
killall islandhelper
cd $HOME/.config/sketchybar/plugins/Dynamic-Island-Sketchybar/helper && make
$HOME/.config/sketchybar/plugins/Dynamic-Island-Sketchybar/helper/islandhelper $ISLANDHELPER &

# Define Dynamic island custom configs here
source "$PLUGIN_DIR/Dynamic-Island-Sketchybar/config.sh" # Loads Dynamic-Island config

# Set up your own custom sketchybar config here
sketchybar --bar	color=$BAR_COLOR \
					margin=10		 \
					corner_radius=9

source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"
source "$ITEM_DIR/mail.sh"
source "$ITEM_DIR/power.sh"
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/cpu.sh"


source "$PLUGIN_DIR/Dynamic-Island-Sketchybar/item.sh" # Loads Dynamic-Island item

sketchybar --update
