#!/usr/bin/env sh

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors 
source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
DYNAMIC_ISLAND_DIR="$HOME/.config/sketchybar/plugins/Dynamic-Island-Sketchybar"

SPACE_CLICK_SCRIPT="yabai -m space --focus \$SID 2>/dev/null" # The script that is run for clicking on space components

# Define Dynamic island custom configs here
source "$DYNAMIC_ISLAND_DIR/config.sh" # Loads Dynamic-Island config

# helper process
HELPER=git.felix.helper
killall helper
cd $HOME/.config/sketchybar/helper && make
$HOME/.config/sketchybar/helper/helper $HELPER > /dev/null 2>&1 &

ISLANDHELPER=git.crissnb.islandhelper
killall islandhelper
cd $DYNAMIC_ISLAND_DIR/helper && make
$DYNAMIC_ISLAND_DIR/helper/islandhelper $ISLANDHELPER &

FONT="SF Pro"

# Set up your own custom sketchybar config here
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &
sketchybar --bar	color=$BAR_COLOR \
					margin=0		 \
					blur_radius=20                                    \
					corner_radius=0 \
					padding_right=10                                  \
					padding_left=10                                   \

source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"
source "$ITEM_DIR/mail.sh"
source "$ITEM_DIR/power.sh"
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/network.sh"

source "$DYNAMIC_ISLAND_DIR/item.sh" # Loads Dynamic-Island item

sketchybar --update
